language: node_js
  
before_script:
  - npm install -g @angular/cli

script:
  - ng build --env=prod --bh /projet-angular/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master