language: node_js

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --bh /projet-angular/
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    repo: remyguillaumot/projet-angular